### PR TITLE
Tiddy up stats directory

### PR DESCRIPTION
**Pull request by kingthorin**
Note this is for the `gh-pages` branch. The GitHub workflow we've discussed will be created against `master`, as apparently only actions from the default branch are displayed/work. So I'll submit the workflow in another PR.

Year named folders were created `2015` through `2019` and `*YYYY*.json` moved to each (where `YYYY` is the relevant year).

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
Missing changes?

**Comment by kingthorin** [comment]
How so? 2754 files moved into 5 folders. 

The GitHub web UI might have trouble displaying it all?

**Comment by kingthorin** [comment]
OH I see it, I think it's a windows/eclipse issue. Tweak coming.

**Comment by kingthorin** [comment]
There that should look better.

**Pull request merged**
